UPDATE mysql.user SET host='%' WHERE user='root';
FLUSH PRIVILEGES;
ALTER USER 'root'@'%' IDENTIFIED BY '$ROOT_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE ON $PMA_DB.* TO '$PMA_USER'@'localhost' IDENTIFIED BY '$PMA_PASSWORD';
